default_platform(:ios)

platform :ios do
  desc "빌드하고 TestFlight에 업로드"
  lane :beta do

    match(type: "appstore", readonly: true)

    increment_version_number(
      version_number: "1.0.2",
      xcodeproj: "MMM_SideProject.xcodeproj"
    )

    build_app(
      scheme: "MMM_SideProject",
      clean: true,
      export_method: "app-store",
      export_options: {
        signingStyle: "manual"
      }
    )

    api_key = app_store_connect_api_key(
      key_id: "",
      issuer_id: "",
      key_filepath: "",
      in_house: false
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: false,
      submit_beta_review: false,
      distribute_external: false,
      changelog: "새로운 기능 및 버그 수정"
    )
  end
end